# Generated by Django 2.0.1 on 2018-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='symbols',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
