# Generated by Django 2.0.1 on 2018-05-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180529_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_info',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
