# Generated by Django 2.0.1 on 2018-05-29 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userportfolio',
            name='portfolio_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.StockInfo'),
        ),
    ]
