# Generated by Django 2.0.1 on 2018-05-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180529_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userportfolio',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='userportfolio',
            name='portfolio_info',
        ),
        migrations.DeleteModel(
            name='UserPortfolio',
        ),
    ]
