# Generated by Django 2.0.1 on 2018-06-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_portfolio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockcompany',
            table='stock_company',
        ),
        migrations.AlterModelTable(
            name='stockinfo',
            table='stock_info',
        ),
    ]
