# Generated by Django 2.0.1 on 2018-06-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180604_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedStock',
            fields=[
                ('company_code', models.CharField(blank=True, db_column='company_CODE', max_length=30, null=True)),
                ('stockpriceid', models.AutoField(db_column='stockpriceID', primary_key=True, serialize=False)),
                ('priceday1', models.FloatField(blank=True, db_column='priceDay1', null=True)),
                ('priceday2', models.FloatField(blank=True, db_column='priceDay2', null=True)),
                ('priceday3', models.FloatField(blank=True, db_column='priceDay3', null=True)),
                ('priceday4', models.FloatField(blank=True, db_column='priceDay4', null=True)),
                ('priceday5', models.FloatField(blank=True, db_column='priceDay5', null=True)),
                ('priceday6', models.FloatField(blank=True, db_column='priceDay6', null=True)),
                ('priceday7', models.FloatField(blank=True, db_column='priceDay7', null=True)),
            ],
            options={
                'db_table': 'predicted_stock',
                'managed': False,
            },
        ),
    ]
